#!/bin/sh
#
# PROVIDE: glyph_spu
# REQUIRE: NETWORKING glyphd
# KEYWORD: shutdown
#
# Add the following lines to /etc/rc.conf to enable glyph_spu:
# glyph_spu_enable="YES"

. /etc/rc.subr

name="glyph_spu"
rcvar=glyph_spu_enable

load_rc_config $name

: ${glyph_spu_enable:="NO"}
: ${glyph_spu_user:="glyphd"}
: ${glyph_spu_group:="glyphd"}
: ${glyph_spu_log:="/var/log/glyph-spu.log"}
: ${glyph_spu_pidfile:="/var/run/glyph-spu.pid"}

command="/usr/local/bin/glyph-spu"
pidfile="${glyph_spu_pidfile}"

start_cmd="${name}_start"
stop_cmd="${name}_stop"
status_cmd="${name}_status"

glyph_spu_start()
{
    echo "Starting ${name}."
    /usr/sbin/daemon -p ${pidfile} -u ${glyph_spu_user} ${command} >> ${glyph_spu_log} 2>&1
}

glyph_spu_stop()
{
    if [ -f ${pidfile} ]; then
        echo "Stopping ${name}."
        kill `cat ${pidfile}`
        rm -f ${pidfile}
    else
        echo "${name} not running."
    fi
}

glyph_spu_status()
{
    if [ -f ${pidfile} ]; then
        echo "${name} is running as pid `cat ${pidfile}`."
    else
        echo "${name} is not running."
    fi
}

run_rc_command "$1"
